package com.imi.rest.db.model;
// Generated Oct 27, 2015 4:52:41 PM by Hibernate Tools 4.0.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name = "country", catalog = "imi")
public class Country implements java.io.Serializable {

    private int id;
    private String countryIsoCode;
    private String country;
    private Set<Providercountry> providercountries = new HashSet<Providercountry>(0);

    public Country() {
    }

    public Country(int id) {
        this.id = id;
    }

    public Country(int id, String countryIsoCode, String country,
            Set<Providercountry> providercountries) {
        this.id = id;
        this.countryIsoCode = countryIsoCode;
        this.country = country;
        this.providercountries = providercountries;
    }

    @Id

    @Column(name = "Id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "CountryIsoCode", length = 45)
    public String getCountryIsoCode() {
        return this.countryIsoCode;
    }

    public void setCountryIsoCode(String countryIsoCode) {
        this.countryIsoCode = countryIsoCode;
    }

    @Column(name = "Country", length = 45)
    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "country")
    public Set<Providercountry> getProvidercountries() {
        return this.providercountries;
    }

    public void setProvidercountries(Set<Providercountry> providercountries) {
        this.providercountries = providercountries;
    }

}
