package com.imi.rest.db.model;

// Generated Oct 6, 2015 6:50:08 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Purchasehistories generated by hbm2java
 */
@Entity
@Table(name = "purchasehistories", catalog = "imi")
public class Purchasehistories implements java.io.Serializable {

    private int id;
    private Provisioning provisioning;
    private Providercountries providercountries;
    private Integer number;
    private String numberType;
    private String restrictions;
    private String monthlyRentalRate;
    private String setUpRate;
    private String smsPrice;
    private String voicePrice;
    private String startDate;
    private String endDate;
    private Integer resourceManagerId;

    public Purchasehistories() {
    }

    public Purchasehistories(int id) {
        this.id = id;
    }

    public Purchasehistories(int id, Provisioning provisioning,
            Providercountries providercountries, Integer number,
            String numberType, String restrictions, String monthlyRentalRate,
            String setUpRate, String smsPrice, String voicePrice,
            String startDate, String endDate, Integer resourceManagerId) {
        this.id = id;
        this.provisioning = provisioning;
        this.providercountries = providercountries;
        this.number = number;
        this.numberType = numberType;
        this.restrictions = restrictions;
        this.monthlyRentalRate = monthlyRentalRate;
        this.setUpRate = setUpRate;
        this.smsPrice = smsPrice;
        this.voicePrice = voicePrice;
        this.startDate = startDate;
        this.endDate = endDate;
        this.resourceManagerId = resourceManagerId;
    }

    @Id
    @Column(name = "Id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "provisioningId")
    public Provisioning getProvisioning() {
        return this.provisioning;
    }

    public void setProvisioning(Provisioning provisioning) {
        this.provisioning = provisioning;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CountryProviderId")
    public Providercountries getProvidercountries() {
        return this.providercountries;
    }

    public void setProvidercountries(Providercountries providercountries) {
        this.providercountries = providercountries;
    }

    @Column(name = "Number")
    public Integer getNumber() {
        return this.number;
    }

    public void setNumber(Integer number) {
        this.number = number;
    }

    @Column(name = "NumberType", length = 45)
    public String getNumberType() {
        return this.numberType;
    }

    public void setNumberType(String numberType) {
        this.numberType = numberType;
    }

    @Column(name = "Restrictions", length = 45)
    public String getRestrictions() {
        return this.restrictions;
    }

    public void setRestrictions(String restrictions) {
        this.restrictions = restrictions;
    }

    @Column(name = "MonthlyRentalRate", length = 45)
    public String getMonthlyRentalRate() {
        return this.monthlyRentalRate;
    }

    public void setMonthlyRentalRate(String monthlyRentalRate) {
        this.monthlyRentalRate = monthlyRentalRate;
    }

    @Column(name = "SetUpRate", length = 45)
    public String getSetUpRate() {
        return this.setUpRate;
    }

    public void setSetUpRate(String setUpRate) {
        this.setUpRate = setUpRate;
    }

    @Column(name = "SmsPrice", length = 45)
    public String getSmsPrice() {
        return this.smsPrice;
    }

    public void setSmsPrice(String smsPrice) {
        this.smsPrice = smsPrice;
    }

    @Column(name = "VoicePrice", length = 45)
    public String getVoicePrice() {
        return this.voicePrice;
    }

    public void setVoicePrice(String voicePrice) {
        this.voicePrice = voicePrice;
    }

    @Column(name = "StartDate", length = 45)
    public String getStartDate() {
        return this.startDate;
    }

    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }

    @Column(name = "EndDate", length = 45)
    public String getEndDate() {
        return this.endDate;
    }

    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }

    @Column(name = "ResourceManagerId")
    public Integer getResourceManagerId() {
        return this.resourceManagerId;
    }

    public void setResourceManagerId(Integer resourceManagerId) {
        this.resourceManagerId = resourceManagerId;
    }

}
