package com.imi.rest.db.model;

// Generated Oct 6, 2015 6:50:08 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Purchases generated by hbm2java
 */
@Entity
@Table(name = "purchases", catalog = "imi")
public class Purchases implements java.io.Serializable {

    private int id;
    private Providercountries providercountries;
    private Integer number;
    private String numberType;
    private String restrictions;
    private String monthlyRentalRate;
    private String setUpRate;
    private String smsRate;
    private String voicePrice;
    private String effectiveDate;
    private Integer resouceManagerId;

    public Purchases() {
    }

    public Purchases(int id) {
        this.id = id;
    }

    public Purchases(int id, Providercountries providercountries,
            Integer number, String numberType, String restrictions,
            String monthlyRentalRate, String setUpRate, String smsRate,
            String voicePrice, String effectiveDate, Integer resouceManagerId) {
        this.id = id;
        this.providercountries = providercountries;
        this.number = number;
        this.numberType = numberType;
        this.restrictions = restrictions;
        this.monthlyRentalRate = monthlyRentalRate;
        this.setUpRate = setUpRate;
        this.smsRate = smsRate;
        this.voicePrice = voicePrice;
        this.effectiveDate = effectiveDate;
        this.resouceManagerId = resouceManagerId;
    }

    @Id
    @Column(name = "Id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CountryProviderId")
    public Providercountries getProvidercountries() {
        return this.providercountries;
    }

    public void setProvidercountries(Providercountries providercountries) {
        this.providercountries = providercountries;
    }

    @Column(name = "Number")
    public Integer getNumber() {
        return this.number;
    }

    public void setNumber(Integer number) {
        this.number = number;
    }

    @Column(name = "NumberType", length = 45)
    public String getNumberType() {
        return this.numberType;
    }

    public void setNumberType(String numberType) {
        this.numberType = numberType;
    }

    @Column(name = "Restrictions", length = 45)
    public String getRestrictions() {
        return this.restrictions;
    }

    public void setRestrictions(String restrictions) {
        this.restrictions = restrictions;
    }

    @Column(name = "MonthlyRentalRate", length = 45)
    public String getMonthlyRentalRate() {
        return this.monthlyRentalRate;
    }

    public void setMonthlyRentalRate(String monthlyRentalRate) {
        this.monthlyRentalRate = monthlyRentalRate;
    }

    @Column(name = "SetUpRate", length = 45)
    public String getSetUpRate() {
        return this.setUpRate;
    }

    public void setSetUpRate(String setUpRate) {
        this.setUpRate = setUpRate;
    }

    @Column(name = "SmsRate", length = 45)
    public String getSmsRate() {
        return this.smsRate;
    }

    public void setSmsRate(String smsRate) {
        this.smsRate = smsRate;
    }

    @Column(name = "VoicePrice", length = 45)
    public String getVoicePrice() {
        return this.voicePrice;
    }

    public void setVoicePrice(String voicePrice) {
        this.voicePrice = voicePrice;
    }

    @Column(name = "EffectiveDate", length = 45)
    public String getEffectiveDate() {
        return this.effectiveDate;
    }

    public void setEffectiveDate(String effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    @Column(name = "ResouceManagerId")
    public Integer getResouceManagerId() {
        return this.resouceManagerId;
    }

    public void setResouceManagerId(Integer resouceManagerId) {
        this.resouceManagerId = resouceManagerId;
    }

}
