package com.imi.rest.dao.model;

// Generated 25 Nov, 2015 2:51:32 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NumberProvider generated by hbm2java
 */
@Entity
@Table(name = "provider", schema = "ump_resource_mgr")
public class Provider implements java.io.Serializable {

    private Integer id;
    private String apiKey;
    private String authId;
    private String name;
    private String sms_callback_url;
    private Set<Providercountry> numberProviderCountries = new HashSet<Providercountry>(
            0);

    public Provider() {
    }

    public Provider(String apiKey, String authId, String name,
            Set<Providercountry> numberProviderCountries) {
        this.apiKey = apiKey;
        this.authId = authId;
        this.name = name;
        this.numberProviderCountries = numberProviderCountries;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "Id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "apiKey", length = 45)
    public String getApiKey() {
        return this.apiKey;
    }

    public void setApiKey(String apiKey) {
        this.apiKey = apiKey;
    }

    @Column(name = "authId", length = 45)
    public String getAuthId() {
        return this.authId;
    }

    public void setAuthId(String authId) {
        this.authId = authId;
    }

    @Column(name = "name", length = 45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "sms_callback_url", length = 45)
    public String getSms_callback_url() {
        return sms_callback_url;
    }

    public void setSms_callback_url(String sms_callback_url) {
        this.sms_callback_url = sms_callback_url;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "numberProvider")
    public Set<Providercountry> getNumberProviderCountries() {
        return this.numberProviderCountries;
    }

    public void setNumberProviderCountries(
            Set<Providercountry> numberProviderCountries) {
        this.numberProviderCountries = numberProviderCountries;
    }

}
