package com.imi.rest.dao.model;

// Generated 25 Nov, 2015 2:51:32 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NumberProvisioning generated by hbm2java
 */
@Entity
@Table(name = "provisioning", schema = "ump_resource_mgr")
public class Provisioning implements java.io.Serializable {

    private Integer id;
    private String voiceUrl;
    private String voiceMethod;
    private String voiceFallbackUrl;
    private String voiceFallbackMethod;
    private String statusCallBack;
    private String statusCallbackMethod;
    private String smsUrl;
    private String smsMethod;
    private String smsFallbackUrl;
    private String smsFallbackMethod;
    private String smsStatusCallback;
    private String number;
    private Set<PurchaseHistory> numberPurchaseHistories = new HashSet<PurchaseHistory>(
            0);

    public Provisioning() {
    }

    public Provisioning(String voiceUrl, String voiceMethod,
            String voiceFallbackUrl, String voiceFallbackMethod,
            String statusCallBack, String statusCallbackMethod, String smsUrl,
            String smsMethod, String smsFallbackUrl, String smsFallbackMethod,
            String smsStatusCallback,
            Set<PurchaseHistory> numberPurchaseHistories) {
        this.voiceUrl = voiceUrl;
        this.voiceMethod = voiceMethod;
        this.voiceFallbackUrl = voiceFallbackUrl;
        this.voiceFallbackMethod = voiceFallbackMethod;
        this.statusCallBack = statusCallBack;
        this.statusCallbackMethod = statusCallbackMethod;
        this.smsUrl = smsUrl;
        this.smsMethod = smsMethod;
        this.smsFallbackUrl = smsFallbackUrl;
        this.smsFallbackMethod = smsFallbackMethod;
        this.smsStatusCallback = smsStatusCallback;
        this.numberPurchaseHistories = numberPurchaseHistories;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "Id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "VoiceUrl")
    public String getVoiceUrl() {
        return this.voiceUrl;
    }

    public void setVoiceUrl(String voiceUrl) {
        this.voiceUrl = voiceUrl;
    }

    @Column(name = "VoiceMethod")
    public String getVoiceMethod() {
        return this.voiceMethod;
    }

    public void setVoiceMethod(String voiceMethod) {
        this.voiceMethod = voiceMethod;
    }

    @Column(name = "VoiceFallbackUrl")
    public String getVoiceFallbackUrl() {
        return this.voiceFallbackUrl;
    }

    public void setVoiceFallbackUrl(String voiceFallbackUrl) {
        this.voiceFallbackUrl = voiceFallbackUrl;
    }

    @Column(name = "VoiceFallbackMethod")
    public String getVoiceFallbackMethod() {
        return this.voiceFallbackMethod;
    }

    public void setVoiceFallbackMethod(String voiceFallbackMethod) {
        this.voiceFallbackMethod = voiceFallbackMethod;
    }

    @Column(name = "StatusCallBack")
    public String getStatusCallBack() {
        return this.statusCallBack;
    }

    public void setStatusCallBack(String statusCallBack) {
        this.statusCallBack = statusCallBack;
    }

    @Column(name = "StatusCallbackMethod")
    public String getStatusCallbackMethod() {
        return this.statusCallbackMethod;
    }

    public void setStatusCallbackMethod(String statusCallbackMethod) {
        this.statusCallbackMethod = statusCallbackMethod;
    }

    @Column(name = "SmsUrl")
    public String getSmsUrl() {
        return this.smsUrl;
    }

    public void setSmsUrl(String smsUrl) {
        this.smsUrl = smsUrl;
    }

    @Column(name = "SmsMethod")
    public String getSmsMethod() {
        return this.smsMethod;
    }

    public void setSmsMethod(String smsMethod) {
        this.smsMethod = smsMethod;
    }

    @Column(name = "SmsFallbackUrl")
    public String getSmsFallbackUrl() {
        return this.smsFallbackUrl;
    }

    public void setSmsFallbackUrl(String smsFallbackUrl) {
        this.smsFallbackUrl = smsFallbackUrl;
    }

    @Column(name = "SmsFallbackMethod")
    public String getSmsFallbackMethod() {
        return this.smsFallbackMethod;
    }

    public void setSmsFallbackMethod(String smsFallbackMethod) {
        this.smsFallbackMethod = smsFallbackMethod;
    }

    @Column(name = "SmsStatusCallback")
    public String getSmsStatusCallback() {
        return this.smsStatusCallback;
    }

    public void setSmsStatusCallback(String smsStatusCallback) {
        this.smsStatusCallback = smsStatusCallback;
    }
    
    @Column(name = "number")
    public String getNumber() {
        return this.number;
    }
    
    public void setNumber(String number) {
        this.number=number;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "numberProvisioning")
    public Set<PurchaseHistory> getNumberPurchaseHistories() {
        return this.numberPurchaseHistories;
    }

    public void setNumberPurchaseHistories(
            Set<PurchaseHistory> numberPurchaseHistories) {
        this.numberPurchaseHistories = numberPurchaseHistories;
    }

}
