package com.imi.rest.dao.model;

// Generated 25 Nov, 2015 2:51:32 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * NumberPurchaseHistory generated by hbm2java
 */
@Entity
@Table(name = "purchasehistory", schema = "ump_resource_mgr")
public class PurchaseHistory implements java.io.Serializable {

	private Integer id;
	private Providercountry numberProviderCountry;
	private Provisioning numberProvisioning;
	private String number;
	private String numberType;
	private String restrictions;
	private String monthlyRentalRate;
	private String setUpRate;
	private String smsPrice;
	private String voicePrice;
	private String startDate;
	private String endDate;
	private Integer resourceManagerId;

	public PurchaseHistory() {
	}

	public PurchaseHistory(Providercountry numberProviderCountry, Provisioning numberProvisioning, String number,
			String numberType, String restrictions, String monthlyRentalRate, String setUpRate, String smsPrice,
			String voicePrice, String startDate, String endDate, Integer resourceManagerId) {
		this.numberProviderCountry = numberProviderCountry;
		this.numberProvisioning = numberProvisioning;
		this.number = number;
		this.numberType = numberType;
		this.restrictions = restrictions;
		this.monthlyRentalRate = monthlyRentalRate;
		this.setUpRate = setUpRate;
		this.smsPrice = smsPrice;
		this.voicePrice = voicePrice;
		this.startDate = startDate;
		this.endDate = endDate;
		this.resourceManagerId = resourceManagerId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "country_provider_id")
	public Providercountry getNumberProviderCountry() {
		return this.numberProviderCountry;
	}

	public void setNumberProviderCountry(Providercountry numberProviderCountry) {
		this.numberProviderCountry = numberProviderCountry;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "provisioning_id")
	public Provisioning getNumberProvisioning() {
		return this.numberProvisioning;
	}

	public void setNumberProvisioning(Provisioning numberProvisioning) {
		this.numberProvisioning = numberProvisioning;
	}

	@Column(name = "number")
	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	@Column(name = "number_type", length = 45)
	public String getNumberType() {
		return this.numberType;
	}

	public void setNumberType(String numberType) {
		this.numberType = numberType;
	}

	@Column(name = "restrictions", length = 45)
	public String getRestrictions() {
		return this.restrictions;
	}

	public void setRestrictions(String restrictions) {
		this.restrictions = restrictions;
	}

	@Column(name = "monthly_rental_rate", length = 45)
	public String getMonthlyRentalRate() {
		return this.monthlyRentalRate;
	}

	public void setMonthlyRentalRate(String monthlyRentalRate) {
		this.monthlyRentalRate = monthlyRentalRate;
	}

	@Column(name = "set_up_rate", length = 45)
	public String getSetUpRate() {
		return this.setUpRate;
	}

	public void setSetUpRate(String setUpRate) {
		this.setUpRate = setUpRate;
	}

	@Column(name = "sms_price", length = 45)
	public String getSmsPrice() {
		return this.smsPrice;
	}

	public void setSmsPrice(String smsPrice) {
		this.smsPrice = smsPrice;
	}

	@Column(name = "voice_price", length = 45)
	public String getVoicePrice() {
		return this.voicePrice;
	}

	public void setVoicePrice(String voicePrice) {
		this.voicePrice = voicePrice;
	}

	@Column(name = "start_date", length = 45)
	public String getStartDate() {
		return this.startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	@Column(name = "end_date", length = 45)
	public String getEndDate() {
		return this.endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	@Column(name = "resource_manager_id")
	public Integer getResourceManagerId() {
		return this.resourceManagerId;
	}

	public void setResourceManagerId(Integer resourceManagerId) {
		this.resourceManagerId = resourceManagerId;
	}

}
